# Generated by Django 3.2.3 on 2021-05-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_list_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
